name: unicorn
channels:
  - fvcore
  - iopath
  - pytorch
  - pytorch3d
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.2
  - fvcore=0.1.5
  - gdown=4.4.0
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.7
  - iopath=0.1.9
  - numpy=1.22.3
  - python=3.9.12
  - python-lmdb=1.3.0
  - pytorch=1.10.2
  - pytorch3d=0.6.2
  - scipy=1.6.2
  - seaborn=0.11.2
  - torchvision=0.11.3
  - toolz=0.11.2
