dataset:
  name: shapenet_nmr
  categories: [table]
model:
  name: unicorn
  encoder:
    name: resnet18
    shared: False
  mesh:
    init: ellipse
    scale: 0.4
    use_mean_txt: True
    deform_fields:
      powers: [2, 8, 64]
      milestones: [11, 67, 123]
      n_field_units: 512
    texture_uv:
      img_size: 64
      min_features: 64
      powers: [2, 8, 64, 512]
      milestones: [0, 11, 67, 123]
  renderer:
    cameras:
      name: perspective
      focal_length: 3.732050895690918
    faces_per_pixel: 50
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [30, 30]
    roll_range: [0, 0]
    T_range: [0.2, 0.2, 0]
    scale_range: [0.5, 0.5, 0.5]
  milestones:
    freeze_scale_predictor: 2
    constant_txt: 10
  loss:
    name: mse
    rgb_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.02
    swap_weight: 1
    swap_memsize: 1024
    swap_n_vpbins: 5
training:
  batch_size: 32
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  scheduler:
    name: multi_step
    gamma: 0.2
    milestones: [179]
  n_epoches: 190
  save_epoches: [10, 67, 123]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 4602
  visualizer_port:
  resume:
