dataset:
  name: comp_cars
  img_size: 64
model:
  name: unicorn
  encoder:
    shared: False
  mesh:
    init: ellipse
    scale: 0.6
    use_mean_txt: True
    deform_fields:
      powers: [2, 8, 64]
      milestones: [175, 350, 525]
    texture_uv:
      img_size: 64
      min_features: 64
      powers: [2, 8, 64, 512]
      milestones: [0, 175, 350, 525]
  background:
    min_features: 64
    powers: [4, 8, 64, 256]
    milestones: [0, 175, 350, 525]
  renderer:
    cameras:
      name: fov
      fov: 30
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [-10, 30]
    roll_range: [-30, 30]
    T_range: [0.3, 0.3, 0.3]
    scale_range: [0.3, 0.3, 0.3]
  milestones:
    freeze_T_predictor: 2
    freeze_shape: 4
    freeze_scale_predictor: 60
    mean_txt: 525
  loss:
    name: mse
    rgb_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.02
    swap_weight: 1
training:
  batch_size: 32
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  n_epoches: 700
  save_epoches: [175, 350, 525]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 993166
  visualizer_port:
  resume: 
